version: "3"

services:

  server:
    build: server/

    ports: 
      - 8888:80
    depends_on:
      - db
  

  db:
    build: db/
    volumes:
      - ./db/data:/data
    ports:
      - 6379:6379
